### ISSUE TITLE
Disable card id:s

### ISSUE THREAD

**Issue by EmilStenstrom** [christiankaindl/trello-super-powers#1]
This is an awesome extension, thanks for you hard work! I'm not interested in card id:s, so I'm suggesting a way to disable them, maybe via a about:config setting?

**Comment by christiankaindl** [comment]
Thanks for reaching out :)

Yeah, that's a great idea! I will look into it for the next release.
If you have any suggestions on how to implement it (about:addons settings or toolbar dropdown button maybe?), feel free to share them here.

**Comment by EmilStenstrom** [comment]
You can decide which one is easiest for you to implement of course :)

The way that some other addons are doing it is to add a settings button to the list of addons (about:addons as you correctly suggested). See the screenshoot below (It's in swedish, "Inställningar" is "Settings" in english). 

<img width="754" alt="skarmavbild 2017-11-06 kl 15 06 55" src="https://user-images.githubusercontent.com/224130/32444825-328fa3bc-c304-11e7-9d63-f4e376bedd4a.png">

**Comment by christiankaindl** [comment]
A settings page is now integrated into the add-ons page (about:addons) although not releaed. Here's the current iteration of the settings page for the upcoming 0.7 release:
![screenshot from 2017-11-11 21-40-41](https://user-images.githubusercontent.com/15364860/32693311-2c5df7c2-c729-11e7-9a4e-937e617c3285.png)

I hope to release it in the coming week! 🔥

**Comment by EmilStenstrom** [comment]
Woha! That looks awesome! :)

- Visible labels actually now built into default Trello, you just click the colored bars and they show the name instead.
- Too avoid someone asking in the future: Maybe a setting for card sums on top too?

Looking forward to the new release!

**Comment by christiankaindl** [comment]
New version is now in review and should be live in a couple of minutes!

The new settings page allows you to toggle

- Compact Mode
- Card IDs on hover
- Visible label text
- Number of cards per list indicator

Thanks for reaching out and maybe you want to give some feedback when you have used it :)

**Comment by christiankaindl** [comment]
Fixed with v0.7

**Comment by EmilStenstrom** [comment]
Awesome! ❤️
