### ISSUE TITLE
Feature request: Default setting for compact mode 

### ISSUE THREAD

**Issue by sbuschjaeger** [christiankaindl/trello-super-powers#18]
Hi,

I really like the compact mode (this is the main reason I installed this addon). Currently, whenever I visit trello.com, my first click is to switch to the compact mode. Is there any way to activate it by default / remember the last setting? 

Best

**Comment by christiankaindl** [comment]
Hi, thanks for weighing in!

This sounds like a good enhancement, I will add it to the next release.

Lg
Christian

**Comment by christiankaindl** [comment]
Addd to version 0.10.0: https://github.com/christiankaindl/trello-super-powers/releases/tag/0.10.0

The new setting looks like this and is disabled by default ("Enable Automatically"):
![tsp_new feature](https://user-images.githubusercontent.com/15364860/47968976-742f8e00-e071-11e8-8dc0-5b7becfe0c2d.png)

When checked, Compact Mode will be applied automatically when you load a Trello board.

I will put it on AMO (addons.mozilla.org) in a couple of days, but I'll notify here when it's live.

**Comment by christiankaindl** [comment]
Hello @sbuschjaeger, I now released version 0.10.0 with your requested feature to AMO. You should be able to update the Add-on via Firefox's Add-on manager now. Thanks for submitting an issue :clap:
