### ISSUE TITLE
Feature idea: Compact Mode in calendar view

### ISSUE THREAD

**Issue by Elise15** [christiankaindl/trello-super-powers#19]
First: Thank you so much for TSP, it is so helpful and much appreciated.

I love using compact mode since it declutters my boards and makes everything more organized. However, I was wondering if it was possible to have compact mode in calendar view. Is there some technical issue preventing it from working or is it simply not part of TSP at this point?

Again, thank you so much.

**Comment by christiankaindl** [comment]
Thanks for reaching out!

Well, I haven't thought of that before so I'm not aware of the technicalities yet. Also, I am not using the calendar myself, but that sounds like a good enhancement.

Would you mind sharing a screenshot how your calendar looks? In the meantime, I will have a look at the technical side. Great to hear that you enjoy the Add-On, thanks for using it :fire:

**Comment by christiankaindl** [comment]
Thanks for the screenshot. I looked into it now and wrote a fix already. Watch out for a release soon.

**Comment by christiankaindl** [comment]
The new version is now available at https://addons.mozilla.org/en-US/firefox/addon/trello-super-powers/

You can update via Firefox's Add-on page (type about:addons in the url bar, or click on Firefox's menu in the top right and choose "Add-ons").

![tsp_2](https://user-images.githubusercontent.com/15364860/51755350-bdb2d680-20be-11e9-9c72-f09769a57a6c.png)
![tsp](https://user-images.githubusercontent.com/15364860/51755351-be4b6d00-20be-11e9-8765-d0e12ddb0a04.png)

**Comment by Elise15** [comment]
Thank you so much for your help! This is exactly the view that I have been craving for the past year.
