### ISSUE TITLE
Export to CSV

### ISSUE THREAD

**Issue by az0** [christiankaindl/trello-super-powers#2]
Users can pay for Trello Premium to export boards to CSV, and users can do it for free using the free JSON export converted to CSV. To make this easier, would you consider adding export to CSV through the extension? 

Rather than CSV, it could also work to format it as an HTML table (maybe in a new tab), which can be copied to a spreadsheet.

Some columns that would be useful include

- [ ] Card  ID
- [ ] Card name
- [ ] List name
- [ ] Label names
- [ ] Date card created

**Comment by christiankaindl** [comment]
That's a cool idea! How do you convert the JSON data to CSV? 

Thanks for the suggestion :)

**Comment by az0** [comment]
I have not yet started pulling data out of Trello.

A possibility may be to integrate with one of the many online JSON to CSV web sites, though I do not know how they handle non-flat structures.

Doing a little research, another option is [Papa Parse](http://papaparse.com/docs#json-to-csv)

**Comment by christiankaindl** [comment]
As version 0.8 is out now, this is one of the main focuses! I am probably going to use a page action (an icon in the URL bar), meaning that whenever you visit a Trello board a small icon in the URL-bar ill show up that let's you export the current board.

**Comment by christiankaindl** [comment]
OK, **initial functionality is done**, it can export your current Trello board as a CSV file. Following columns are enabled right now (all in card context):

- name
- url
- shortUrl
- idShort
- description
- labels
- due date

"Date created" is not present in the JSON data, so I can't include it in the CSV file.
Some things could be added before the release such as translation and a simple UI for things like the delimiter, output file name and an option to include also archived cards.

If you want to test it, you can grab the beta version from here: https://addons.mozilla.org/en-US/firefox/addon/trello-super-powers/versions/beta

When installed you should see a little icon in the URL bar when visiting a Trello board:
![screenshot from 2017-12-14 14 22 44](https://user-images.githubusercontent.com/15364860/33994758-0f333082-e0dc-11e7-8850-35fc15f6cda3.png)

Click it and the current board will be downloaded as a CSV file :)

Please drop feedback here when you have tested it, thanks!

**Comment by christiankaindl** [comment]
Ok, UI is done now, it allows you to choose a name for your export, let's you choose between "," and ";" ad a delimiter of the CSV fields, and it gives you an option to also include archived cards. Here's how it looks:

![screenshot from 2017-12-16 11 49 42](https://user-images.githubusercontent.com/15364860/34082100-6f0e6f48-e358-11e7-9275-6c377684c630.png)

I guess the only thing left before release are the translation from the popup UI

PS: You can already try it out in the Beta channel

**Comment by az0** [comment]
I tried this out on my most active board with 188 cards. The URL icon was subtle that I may not have found it without your instructions. 

The export was relatively quick, and it imported fine into MS Excel. I am worried that carriage returns or commas in the values, in particular in the description, will confuse some other applications when importing. All applications _should_ be able to deal with these cases, but some applications simply don't do it well, so it could be nice to have an option to either exclude columns such as description (because it is prone to confusing some applications) or to sanitize the values (by stripping/replacing carriage returns and delimiters).

If you would like, you can close this ticket.

If you could please add the list name (correlated from `idList), I could use this to mostly automate reports on outstanding requests. I use the list to mark it basically "in progress" or "complete," and in my report I can count cards by list.

The board ID would be nice to have because I am going to stack together exports from three boards, though I could add this on my end too.

Thank you!!!

**Comment by az0** [comment]
P.S.,

Yes, I see that the date the card was created is not in the JSON. Too bad. It is in the activity feed when I open the card, but this may not be practical to access.

The beta channel had versions 0.9a and 0.9.1a with the same release date, and I tested 0.9.1a.

**Comment by christiankaindl** [comment]
To your points: board ID is easy to add, list ID also. String sanitation is important and should be done, that is true (also for the filename input). For list names I have to come up with a way yet.

I'll do a new Beta release tomorrow with board IDs and list IDs, so that you can already use them. And before the actual release to the public, sanitation has to be done in some form.

Thank you for the feedback! ❤️

**Comment by christiankaindl** [comment]
New Beta version is live: 0.9.2a
https://addons.mozilla.org/en-US/firefox/addon/trello-super-powers/versions/beta

It comes with board ID, list ID and list names! Enjoy 🔥

**Comment by christiankaindl** [comment]
Version 0.9 is now live on AMO... with file export!

Read more about the details here: https://listed.standardnotes.org/@christiankaindl/1064/trello-super-powers-add-on-v0-9-release-notes
