### ISSUE TITLE
Add option to allways see card ID

### ISSUE THREAD

**Issue by drizt** [christiankaindl/trello-super-powers#21]
Now need to hove on card to see it ID. Please add an option to always show all card IDs on board. Also allow to see ID in opened card.

**Comment by christiankaindl** [comment]
Hello, thanks for reaching out :+1: 

These sound like good additions to me. I don't know yet when I will be able to work on this as my time is somewhat limited right now.

Anyways, I leave this open and maybe someone contributes a patch (would be a good first issue I think).

**Comment by christiankaindl** [comment]
Permanently showing card IDs is now implemented in 0.12.0 :star: thanks to @Rj7 's contribution.
The new version is now available at https://addons.mozilla.org/en-US/firefox/addon/trello-super-powers/
