### ISSUE TITLE
Settings option to disable resizable lists

### ISSUE THREAD

**Issue by Cassidy13K** [christiankaindl/trello-super-powers#22]
Good afternoon, 

I enjoy using your extension for it's features "Card IDs on hover" and "Number of cards per list" on latest Firefox Quantum. I appreciate that you offer options to disable the other features, however I have noticed that there is no option to disable "resizable lists".
This feature breaks the trello board list spacing when used in combination with other trello extensions, such as "Strelloids" or "Trello collapsible lists". I'm using the latter to collapse lists, however when using your extension, these collapsed lists are not nicely aligned - there is a lot of empty space between them. 
As soon as i disable your extension the columns are nicely aligned. See examples below:

Example using Strelloids without your extension:
![Example using Strelloids without your extension](https://user-images.githubusercontent.com/26398668/57457331-9ba92280-726f-11e9-9997-99e48e89335a.png)
Example using Strelloids with your extension enabled:
![Example using Strelloids with your extension enabled](https://user-images.githubusercontent.com/26398668/57457376-b7142d80-726f-11e9-81ce-a35534abf852.png)

I assume this is caused by the resizable lists feature and hence would appreciate it if you could add an option to disable this so I can continue to use your extension for the other features it provides. :)
Of course my assumption might be wrong, but even then, having an option to disable it is hopefully not too much work and would also prevent users from accidentally resizing lists (happens a lot to me too).

Thank you and have a great day

**Comment by christiankaindl** [comment]
Thanks for pointing that out. I looked into it, and indeed Trello Super Powers is causing the issue here. We were setting a min-width on the list-wrapper class which is the issue.

The fix for the huge gap is actually really simple, I just have to remove the `min-width` CSS statement. I am trying to push a new release sometime tomorrow.

Regarding accidental resizes: Could you elaborate what you mean by that? Or, how is it triggered accidentally?

**Comment by Cassidy13K** [comment]
Thank you for the quick reply, I appreciate it. Looking forward to the update to try it out and close this issue. :)

In regards to the accidental resizing, that a problem had in the past, when retrying again it seems like resizing is not working at all for me. Since that is a different problem, I've opened another issue, please reference:  #23

**Comment by christiankaindl** [comment]
Yeah, I noticed that too. The resize feature is very broken right now. Thanks for opening another issue for it :clap:

**Comment by christiankaindl** [comment]
The new version is now available at https://addons.mozilla.org/en-US/firefox/addon/trello-super-powers/

You can update via Firefox's Add-on page (type about:addons in the url bar, or click on Firefox's menu in the top right and choose "Add-ons").

It's now the best of both worlds (assuming the resizable lists feature injects successfully):


![peekFD6C1Z webm](https://user-images.githubusercontent.com/15364860/57570352-279e8400-7401-11e9-81fa-808e3a4b0b80.gif)
