### ISSUE TITLE
Resize list icon not appearing on FireFox

### ISSUE THREAD

**Issue by Cassidy13K** [christiankaindl/trello-super-powers#23]
Resize icon / resize feature is currently not for me, please see specs and steps below.
Firefox Quantum 66.0.5 (64-bit) Windows 10

- enable your extension
- disable any other extensions
- ctrl + F5 the page for good measure
- create 2 lists with some cards
- try moving mouse between the lists 
--> no resize icon appears
- try dragging between the lists
--> lists do not get resized

![17s_33m_15h_date_10_05_2019](https://user-images.githubusercontent.com/26398668/57531095-fd818f00-7338-11e9-84b6-413d6993d52d.gif)

Thank you and have a nice day. :)

**Comment by Cassidy13K** [comment]
Just to have an update here. This issue is not fully resolved for me after the newest update. It sometimes seems to work like shown in your GIF in #22 , but the functionality only loads some time after the board is open - or not at all. Meaning I have lists collapsed with little space between them (Strelloids extension), wait 30 seconds or more, suddenly the space between them gets a tiny bit bigger and you can resize the lists. 
Often you still cannot resize them (icon does not appear to drag them); CTRL + F5, reopening the browser or disabling & re-enabling the extension does not seem to help.

Using Strelloids + Trello Super Powers Extensions, same specs as in OP. :)

**Comment by dspjm** [comment]
The icon shows on my Firefox browser. It works fine.

**Comment by christiankaindl** [comment]
I just had a look and it seems to work correctly when you load the board directly (via F5 or the reload icon in the browser bar), but it doesn't work anymore when you navigate to a different board within the Trello UI. Will need to take a closer look.

As a temporary workaround, you could reload the current board where you need to have the resize handles.

**Comment by artus70** [comment]
I found the resize handles are temporarily visible for some time while loading the board but disappear when the loading is finished. Happens any time I reload the current board. 

(FF 84.0.1)

**Comment by christiankaindl** [comment]
This should be resolved the last release. Feel free to reopen if you can still reproduce.

Related to #34
