### ISSUE TITLE
Export is not working on larger boards in Firefox

### ISSUE THREAD

**Issue by dspjm** [christiankaindl/trello-super-powers#28]
After you click export, there is a small circle around the cursor for a while, but no further reaction.

It works on a small board I created, but not a big one which contains about 200 cards.

**Comment by christiankaindl** [comment]
Hey, thanks for reporting this issue!

Do you have a public board that also has this issue, so that I could test/debug it further?

**Comment by dspjm** [comment]
I just copied the same board and this doesn't happen in the new board. The differences are the comments, so I assume it's about the comments.

I tried in on another large board I have and this problem didn't happen either.

I will update on this if I find any further information.

**Comment by christiankaindl** [comment]
Closing for now... feel free to re-open if you still have the issue!
