### ISSUE TITLE
CSV export - instructions?

### ISSUE THREAD

**Issue by ocraig** [christiankaindl/trello-super-powers#29]
Howdy Christian;

Thanks for this addon.  As much as I've tried, I can't find any indication of *how* to download as CSV. There's no new button or listing on a dropdown, etc.  I'm guessing it's right in front of my face but, y'know, help a lad out?

**Comment by christiankaindl** [comment]
Hey @ocraig, thanks for reaching out. I am not sure exactly where you are stuck in the export process, so I'm just gonna explain it step by step :)

1. You should see a small icon in the address bar
<img width="133" alt="Screen Shot 2021-01-19 at 09 36 48" src="https://user-images.githubusercontent.com/15364860/105009101-62601880-5a3a-11eb-8280-292e8c27a45e.png">

2. When you click it a popover should show up, like this:
<img width="259" alt="Screen Shot 2021-01-19 at 09 37 03" src="https://user-images.githubusercontent.com/15364860/105009123-68ee9000-5a3a-11eb-9223-ebe8321e62bb.png">

3. **After you hit export and wait until the cursor stops spinning, the exported file lands in the Downloads folder of your computer**

**Comment by ocraig** [comment]
Christian - you nailed it.  I overlooked the new icon in the address bar.  Thank you for the instructions and for the project.
