### ISSUE TITLE
Add a button for enable or disable ajustable width list

### ISSUE THREAD

**Issue by Dayoros** [christiankaindl/trello-super-powers#35]
Hi !
I use this plugin for a long time, and all functionnality are very great !
But, since the last version with the new functionnality "ajustable width list", i've got some problems.
I use Trello in my browser, and i've got a lot of lists.
So when i use my mouse to move to the left or the right to browse all my lists, it may be append that i click on your new separator of list by accident... And my lists width grows up, but i just want to move in a direction ;(

Can you just add a new button in the extention, for activate or desactivate this new functionnality, as the "compact mode button" ?
And the user will choose if he want to use this function, or not.

Thanks a lot !
Sincerely,

**Comment by christiankaindl** [comment]
Hi Dayoros! You're right, there should probably be a setting for it (to be consistent with the other features).

But, I think the out-of-the-box experience should not break your workflow in the first place. There's two issues that I see:
1. The separators make your board even longer as it already is, and
2. The separators make your lists jump to a different place, which causes you to click the wrong thing

I think the proper solution would be to make sure the separators don't add any additional width to the board. That way even if you don't use the feature often it doesn't get in your way, as well as fix both issues.

**Comment by christiankaindl** [comment]
Whoops, closed too early!

**Comment by christiankaindl** [comment]
@Dayoros: in the latest version, 0.13.3, lists should not jump around anymore when the resizable list feature is initialized. Please try it out and let me know what you think!

You can update via Firefox's Add-on page (click on Firefox's menu in the top right and choose "Add-ons", or type "about:addons" in the address bar).

**Comment by Dayoros** [comment]
@christiankaindl : it's clearly better for me ! I've not the same "bad" feeling when i move the board with my mouse... And i can choose easily if i want to increase the width of my list.
Thanks a lot and happy new year :)
