### ISSUE TITLE
[Suggestion] Sort cards alphabetically

### ISSUE THREAD

**Issue by bagage** [christiankaindl/trello-super-powers#7]
Similarly to what [Ultimello](https://chrome.google.com/webstore/detail/ultimello-the-features-pa/hahbfgjfimnmogoinnenhheepfcphnmm?hl=en-US) does on Chrome, it would be realllly cool to be able to sort cards (at least alphabetically) in Firefox.
Thanks for this great addon!

**Comment by christiankaindl** [comment]
Thanks for your feedback :heart:

I will try to look into this and thanks for using TSP :)

**Comment by christiankaindl** [comment]
Apparently, for this kind of feature to work reliably, Authentication has to implemented first (as Ultimello does). This is already planned, but will take some more time, as I first have to learn how that works.
I'll keep you posted 👍

**Comment by dspjm** [comment]
Looks like trello now support sorting, including alphabatic order.

**Comment by christiankaindl** [comment]
True, closing this now!

<img width="322" alt="Screen Shot 2020-08-27 at 10 36 27" src="https://user-images.githubusercontent.com/15364860/91417688-77e96180-e851-11ea-82d5-ad1c76bc4f32.png">
